---
AWSTemplateFormatVersion: "2010-09-09"

Description: |
  Security Group template for allowing OpenVPN access to the Proxy.

Parameters:
  OpenVPNSG:
    Description: SecurityGroup for OpenVPN (output from the OpenVPN CloudFormation script)
    Type: AWS::EC2::SecurityGroup::Id
  ProxySG:
    Description: SecurityGroup for your outer Proxy instance
    Type: AWS::EC2::SecurityGroup::Id

Resources:
  SGBaseIngress1:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId:
        Ref: ProxySG
      IpProtocol: tcp
      FromPort: '22'
      ToPort: '22'
      SourceSecurityGroupId:
        Ref: OpenVPNSG
  SGBaseIngress2:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId:
        Ref: ProxySG
      IpProtocol: tcp
      FromPort: '80'
      ToPort: '80'
      SourceSecurityGroupId:
        Ref: OpenVPNSG
  SGBaseIngress3:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId:
        Ref: ProxySG
      IpProtocol: tcp
      FromPort: '443'
      ToPort: '443'
      SourceSecurityGroupId:
        Ref: OpenVPNSG
...
